from ubuntu:18.04

RUN apt-get update && \
    apt-get install vim -y && \
    apt-get install -y net-tools && \
    apt-get install -y inetutils-ping && \
    apt-get install -y passwd && \
    apt-get install -y openssh-server && \
    apt-get clean && \
    sed -i "s/#Port 22/Port 22/" /etc/ssh/sshd_config && \
    sed -i "s/#ListenAddress 0.0.0.0/ListenAddress 0.0.0.0/" /etc/ssh/sshd_config && \
    sed -i "s/#ListenAddress ::/ListenAddress ::/" /etc/ssh/sshd_config && \
    sed -i "s/#PermitRootLogin yes/PermitRootLogin yes/" /etc/ssh/sshd_config && \
    sed -i "s/#PasswordAuthentication yes/PasswordAuthentication yes/" /etc/ssh/sshd_config && \
    sed -i "s/#PubkeyAuthentication yes/PubkeyAuthentication yes/" /etc/ssh/sshd_config && \
    sed -i "s/#PermitRootLogin prohibit-password/PermitRootLogin yes/" /etc/ssh/sshd_config && \
    ssh-keygen -y -q -t rsa -b 2048 -f /etc/ssh/ssh_host_rsa_key -N "" && \
    ssh-keygen -y -q -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -N "" && \
    ssh-keygen -y -t dsa -f /etc/ssh/ssh_host_ed25519_key -N "" && \
    # /sbin/sshd && \
    ssh-keygen -t rsa -P '' -f ~/.ssh/id_rsa && \
    cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys && \
    chmod 0600 ~/.ssh/authorized_keys && \
    /etc/init.d/ssh start
    #systemctl start sshd.service


